CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE roles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code VARCHAR(40) UNIQUE NOT NULL, name TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), firebase_uid TEXT UNIQUE NOT NULL, email TEXT UNIQUE NOT NULL, name TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE user_roles (user_id UUID REFERENCES users(id) ON DELETE CASCADE, role_id UUID REFERENCES roles(id), PRIMARY KEY (user_id, role_id));
CREATE TABLE warehouses (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, code VARCHAR(20) UNIQUE NOT NULL, address TEXT, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE locations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), warehouse_id UUID REFERENCES warehouses(id), name TEXT NOT NULL, code VARCHAR(30) NOT NULL, parent_location_id UUID REFERENCES locations(id), location_type VARCHAR(30) NOT NULL DEFAULT 'INTERNAL', active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(warehouse_id, code));
CREATE TABLE categories (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT UNIQUE NOT NULL, description TEXT, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE products (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, sku VARCHAR(80) UNIQUE NOT NULL, description TEXT, category_id UUID REFERENCES categories(id), uom VARCHAR(30) NOT NULL DEFAULT 'units', reorder_point NUMERIC(14,2) NOT NULL DEFAULT 0, reorder_quantity NUMERIC(14,2) NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE suppliers (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, email TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE customers (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, email TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE stock_balances (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), product_id UUID NOT NULL REFERENCES products(id), warehouse_id UUID NOT NULL REFERENCES warehouses(id), location_id UUID NOT NULL REFERENCES locations(id), on_hand NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK(on_hand >= 0), reserved NUMERIC(14,2) NOT NULL DEFAULT 0, updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(product_id, location_id));
CREATE TABLE documents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), document_type VARCHAR(30) NOT NULL, document_number VARCHAR(50) UNIQUE NOT NULL, partner_name TEXT, source_warehouse_id UUID REFERENCES warehouses(id), source_location_id UUID REFERENCES locations(id), destination_warehouse_id UUID REFERENCES warehouses(id), destination_location_id UUID REFERENCES locations(id), scheduled_date DATE, status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', notes TEXT, created_by UUID REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE document_lines (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), document_id UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE, product_id UUID NOT NULL REFERENCES products(id), expected_quantity NUMERIC(14,2) NOT NULL CHECK(expected_quantity > 0), processed_quantity NUMERIC(14,2) NOT NULL DEFAULT 0, uom VARCHAR(30) NOT NULL DEFAULT 'units');
CREATE TABLE stock_ledger (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), product_id UUID NOT NULL REFERENCES products(id), warehouse_id UUID NOT NULL REFERENCES warehouses(id), location_id UUID NOT NULL REFERENCES locations(id), movement_type VARCHAR(40) NOT NULL, quantity NUMERIC(14,2) NOT NULL, reference_type VARCHAR(30) NOT NULL, reference_id UUID NOT NULL, before_quantity NUMERIC(14,2) NOT NULL, after_quantity NUMERIC(14,2) NOT NULL, performed_by UUID REFERENCES users(id), notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE reordering_rules (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), product_id UUID NOT NULL REFERENCES products(id), warehouse_id UUID REFERENCES warehouses(id), location_id UUID REFERENCES locations(id), min_quantity NUMERIC(14,2) NOT NULL DEFAULT 0, max_quantity NUMERIC(14,2), reorder_quantity NUMERIC(14,2) NOT NULL DEFAULT 0, preferred_supplier TEXT, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE inventory_adjustments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), product_id UUID NOT NULL REFERENCES products(id), warehouse_id UUID NOT NULL REFERENCES warehouses(id), location_id UUID NOT NULL REFERENCES locations(id), system_quantity NUMERIC(14,2) NOT NULL, counted_quantity NUMERIC(14,2) NOT NULL CHECK(counted_quantity >= 0), reason TEXT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', created_by UUID REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE otp_tokens (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), email TEXT NOT NULL, token_hash TEXT NOT NULL, expires_at TIMESTAMPTZ NOT NULL, attempts SMALLINT NOT NULL DEFAULT 0, consumed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX idx_products_name ON products(name); CREATE INDEX idx_stock_balances_product ON stock_balances(product_id); CREATE INDEX idx_stock_balances_location ON stock_balances(location_id); CREATE INDEX idx_ledger_product ON stock_ledger(product_id); CREATE INDEX idx_ledger_created ON stock_ledger(created_at DESC); CREATE INDEX idx_ledger_reference ON stock_ledger(reference_id); CREATE INDEX idx_documents_status ON documents(status);
