import { Router } from 'express';
import crypto from 'node:crypto';
import admin from 'firebase-admin';
import { query } from '../db/pool.js';
import { ApiError } from '../utils/api-error.js';
import { requireAuth } from '../middleware/auth.js';

const router=Router(); const hash=(value)=>crypto.createHash('sha256').update(value).digest('hex');
async function sendOtpEmail(email, otp){const key=process.env.EMAIL_PROVIDER_API_KEY,from=process.env.EMAIL_FROM;if(!key||!from)throw new ApiError(503,'Password reset email is not configured','OTP_DELIVERY_UNAVAILABLE');const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[email],subject:'Your StockSense password reset code',html:`<p>Your StockSense password reset code is:</p><h1 style="letter-spacing:4px">${otp}</h1><p>This code expires in 10 minutes. If you did not request it, you can ignore this email.</p>`})});if(!response.ok)throw new ApiError(502,'Unable to send the reset email. Please try again.','OTP_DELIVERY_FAILED')}
router.post('/profile',requireAuth,async(req,res,next)=>{try{const {uid,email,name}=req.user;let user=await query('SELECT * FROM users WHERE firebase_uid=$1',[uid]);if(!user.rowCount){user=await query('INSERT INTO users(firebase_uid,email,name) VALUES($1,$2,$3) RETURNING *',[uid,email,name||email.split('@')[0]]);await query(`INSERT INTO user_roles(user_id,role_id) SELECT $1,id FROM roles WHERE code='WAREHOUSE_STAFF'`,[user.rows[0].id]);}res.json({success:true,data:user.rows[0]})}catch(e){next(e)}});
router.post('/request-reset',async(req,res,next)=>{try{const email=String(req.body.email||'').trim().toLowerCase();if(!email.includes('@'))throw new ApiError(422,'Enter a valid email address','VALIDATION_ERROR');const recent=await query("SELECT id FROM otp_tokens WHERE email=$1 AND created_at > now()-interval '60 seconds'",[email]);if(recent.rowCount)throw new ApiError(429,'Please wait a minute before requesting another code','OTP_RATE_LIMITED');const otp=crypto.randomInt(100000,1000000).toString();await sendOtpEmail(email,otp);await query("INSERT INTO otp_tokens(email,token_hash,expires_at) VALUES($1,$2,now()+interval '10 minutes')",[email,hash(otp)]);res.json({success:true,data:{message:'If the account exists, a reset code has been sent.'}})}catch(e){next(e)}});
router.post('/verify-reset-otp',async(req,res,next)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),otp=String(req.body.otp||'');const t=await query('SELECT * FROM otp_tokens WHERE email=$1 AND consumed_at IS NULL ORDER BY created_at DESC LIMIT 1',[email]);if(!t.rowCount||new Date(t.rows[0].expires_at)<new Date())throw new ApiError(400,'This code has expired. Request a new one.','OTP_EXPIRED');if(t.rows[0].attempts>=5)throw new ApiError(429,'Too many attempts. Request a new code.','OTP_ATTEMPTS_EXCEEDED');if(hash(otp)!==t.rows[0].token_hash){await query('UPDATE otp_tokens SET attempts=attempts+1 WHERE id=$1',[t.rows[0].id]);throw new ApiError(400,`That code is incorrect. ${4-t.rows[0].attempts} attempts remaining.`,'OTP_INVALID')}await query('UPDATE otp_tokens SET consumed_at=now() WHERE id=$1',[t.rows[0].id]);res.json({success:true,data:{verified:true}})}catch(e){next(e)}});
router.post('/reset-password',async(req,res,next)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(password.length<8)throw new ApiError(422,'Password must contain at least 8 characters','VALIDATION_ERROR');const verified=await query("SELECT id FROM otp_tokens WHERE email=$1 AND consumed_at IS NOT NULL AND consumed_at > now()-interval '15 minutes' ORDER BY consumed_at DESC LIMIT 1",[email]);if(!verified.rowCount)throw new ApiError(400,'Verify a valid reset code before choosing a new password','OTP_NOT_VERIFIED');if(!admin.apps.length&&process.env.NODE_ENV!=='development')throw new ApiError(503,'Password reset is not configured','AUTH_UNAVAILABLE');if(admin.apps.length){const user=await admin.auth().getUserByEmail(email);await admin.auth().updateUser(user.uid,{password});}await query('DELETE FROM otp_tokens WHERE id=$1',[verified.rows[0].id]);res.json({success:true,data:{message:'Password reset successfully'}})}catch(e){next(e)}});
export default router;
