import { Router } from 'express'; import { query, pool } from '../db/pool.js'; import { validate } from '../middleware/validate.js'; import { authorize } from '../middleware/auth.js'; import { productSchema, warehouseSchema, locationSchema } from '../validators/schemas.js'; import { ApiError } from '../utils/api-error.js'; import { changeStock } from '../services/inventory-service.js';
const router = Router(); const result = (res, data) => res.json({ success:true, data });

router.get('/products', async (req,res,next)=>{ try { const term=`%${req.query.search||''}%`; result(res,(await query(`SELECT p.*,c.name category,COALESCE(SUM(sb.on_hand),0) "onHand",COALESCE(SUM(sb.reserved),0) reserved,COALESCE(SUM(sb.on_hand-sb.reserved),0) available FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN stock_balances sb ON sb.product_id=p.id WHERE p.active AND (p.name ILIKE $1 OR p.sku ILIKE $1) GROUP BY p.id,c.name ORDER BY p.name`,[term])).rows); }catch(e){next(e)} });
router.get('/products/:id', async(req,res,next)=>{try{const p=await query(`SELECT p.*, c.name category FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.id=$1`,[req.params.id]); if(!p.rowCount)throw new ApiError(404,'Product not found','NOT_FOUND'); const balances=await query(`SELECT w.name warehouse,l.name location,sb.on_hand,sb.reserved,sb.on_hand-sb.reserved available FROM stock_balances sb JOIN warehouses w ON w.id=sb.warehouse_id JOIN locations l ON l.id=sb.location_id WHERE sb.product_id=$1`,[req.params.id]); result(res,{...p.rows[0],balances:balances.rows});}catch(e){next(e)}});
router.post('/products', authorize('ADMIN','INVENTORY_MANAGER'),validate(productSchema),async(req,res,next)=>{ const client=await pool.connect();try{await client.query('BEGIN');const b=req.body;const p=await client.query('INSERT INTO products(name,sku,description,category_id,uom,reorder_point,reorder_quantity) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[b.name,b.sku,b.description||null,b.categoryId||null,b.uom,b.reorderPoint,b.reorderQuantity]);if(b.initialStock&&b.locationId&&b.warehouseId)await changeStock(client,{productId:p.rows[0].id,warehouseId:b.warehouseId,locationId:b.locationId,delta:b.initialStock,movementType:'ADJUSTMENT_IN',referenceType:'INITIAL_STOCK',referenceId:p.rows[0].id,userId:req.user.id,notes:'Initial product stock'});await client.query('COMMIT');res.status(201).json({success:true,data:p.rows[0]});}catch(e){await client.query('ROLLBACK');next(e)}finally{client.release()} });
router.put('/products/:id',authorize('ADMIN','INVENTORY_MANAGER'),validate(productSchema.partial()),async(req,res,next)=>{try{const b=req.body;const p=await query(`UPDATE products SET name=COALESCE($1,name),sku=COALESCE($2,sku),description=COALESCE($3,description),category_id=COALESCE($4,category_id),uom=COALESCE($5,uom),reorder_point=COALESCE($6,reorder_point),reorder_quantity=COALESCE($7,reorder_quantity),updated_at=now() WHERE id=$8 RETURNING *`,[b.name,b.sku,b.description,b.categoryId,b.uom,b.reorderPoint,b.reorderQuantity,req.params.id]);if(!p.rowCount)throw new ApiError(404,'Product not found','NOT_FOUND');result(res,p.rows[0]);}catch(e){next(e)}});
router.delete('/products/:id',authorize('ADMIN','INVENTORY_MANAGER'),async(req,res,next)=>{try{await query('UPDATE products SET active=false,updated_at=now() WHERE id=$1',[req.params.id]);res.status(204).end();}catch(e){next(e)}});
router.get('/categories',async(_req,res,next)=>{try{result(res,(await query(`SELECT c.*,COUNT(p.id)::int "productCount" FROM categories c LEFT JOIN products p ON p.category_id=c.id AND p.active WHERE c.active GROUP BY c.id ORDER BY c.name`)).rows)}catch(e){next(e)}});
router.post('/categories',authorize('ADMIN','INVENTORY_MANAGER'),async(req,res,next)=>{try{if(!req.body.name)throw new ApiError(422,'Category name is required','VALIDATION_ERROR');result(res,(await query('INSERT INTO categories(name,description) VALUES($1,$2) RETURNING *',[req.body.name,req.body.description||null])).rows[0])}catch(e){next(e)}});
router.get('/warehouses',async(_req,res,next)=>{try{result(res,(await query('SELECT * FROM warehouses WHERE active ORDER BY name')).rows)}catch(e){next(e)}});
router.post('/warehouses',authorize('ADMIN'),validate(warehouseSchema),async(req,res,next)=>{try{res.status(201);result(res,(await query('INSERT INTO warehouses(name,code,address) VALUES($1,$2,$3) RETURNING *',[req.body.name,req.body.code,req.body.address||null])).rows[0])}catch(e){next(e)}});
router.get('/locations',async(req,res,next)=>{try{result(res,(await query('SELECT l.*,w.name warehouse FROM locations l JOIN warehouses w ON w.id=l.warehouse_id WHERE l.active AND ($1::uuid IS NULL OR l.warehouse_id=$1) ORDER BY w.name,l.name',[req.query.warehouse||null])).rows)}catch(e){next(e)}});
router.post('/locations',authorize('ADMIN','INVENTORY_MANAGER'),validate(locationSchema),async(req,res,next)=>{try{res.status(201);result(res,(await query('INSERT INTO locations(warehouse_id,name,code,location_type) VALUES($1,$2,$3,$4) RETURNING *',[req.body.warehouseId,req.body.name,req.body.code,req.body.locationType])).rows[0])}catch(e){next(e)}});
export default router;
