import { Router } from 'express'; import { query } from '../db/pool.js';
const router=Router();const done="NOT IN ('DONE','CANCELED')";
router.get('/summary',async(_req,res,next)=>{try{const [stock,low,out,receipts,deliveries,transfers]=await Promise.all([
 query('SELECT COUNT(DISTINCT product_id)::int value FROM stock_balances WHERE on_hand>0'),query(`SELECT COUNT(*)::int value FROM (SELECT p.id FROM products p LEFT JOIN stock_balances s ON s.product_id=p.id GROUP BY p.id,p.reorder_point HAVING COALESCE(SUM(s.on_hand-s.reserved),0)<=p.reorder_point AND COALESCE(SUM(s.on_hand-s.reserved),0)>0) x`),query(`SELECT COUNT(*)::int value FROM (SELECT p.id FROM products p LEFT JOIN stock_balances s ON s.product_id=p.id GROUP BY p.id HAVING COALESCE(SUM(s.on_hand-s.reserved),0)<=0) x`),query(`SELECT COUNT(*)::int value FROM documents WHERE document_type='RECEIPT' AND status ${done}`),query(`SELECT COUNT(*)::int value FROM documents WHERE document_type='DELIVERY' AND status ${done}`),query(`SELECT COUNT(*)::int value FROM documents WHERE document_type='TRANSFER' AND status ${done}`)
]);res.json({success:true,data:{totalProducts:stock.rows[0].value,lowStock:low.rows[0].value,outOfStock:out.rows[0].value,pendingReceipts:receipts.rows[0].value,pendingDeliveries:deliveries.rows[0].value,scheduledTransfers:transfers.rows[0].value}})}catch(e){next(e)}});
router.get('/recent-operations',async(_req,res,next)=>{try{res.json({success:true,data:(await query(`SELECT d.*,COALESCE(sw.name,dw.name) warehouse FROM documents d LEFT JOIN warehouses sw ON sw.id=d.source_warehouse_id LEFT JOIN warehouses dw ON dw.id=d.destination_warehouse_id ORDER BY d.created_at DESC LIMIT 8`)).rows})}catch(e){next(e)}});
router.get('/stock-alerts',async(_req,res,next)=>{try{res.json({success:true,data:(await query(`SELECT p.id,p.name,p.sku,p.reorder_point,COALESCE(SUM(s.on_hand-s.reserved),0) available FROM products p LEFT JOIN stock_balances s ON s.product_id=p.id WHERE p.active GROUP BY p.id HAVING COALESCE(SUM(s.on_hand-s.reserved),0)<=p.reorder_point ORDER BY available LIMIT 8`)).rows})}catch(e){next(e)}});
router.get('/stock-by-category',async(_req,res,next)=>{try{res.json({success:true,data:(await query(`SELECT COALESCE(c.name,'Uncategorized') label,COALESCE(SUM(s.on_hand),0) value FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN stock_balances s ON s.product_id=p.id GROUP BY c.name ORDER BY value DESC`)).rows})}catch(e){next(e)}});
export default router;
