import { Router } from 'express'; import { pool, query } from '../db/pool.js'; import { validate } from '../middleware/validate.js'; import { authorize } from '../middleware/auth.js'; import { documentSchema, adjustmentSchema } from '../validators/schemas.js'; import { ApiError } from '../utils/api-error.js'; import { validateDocument, changeStock } from '../services/inventory-service.js';
const router=Router();const types={receipts:'RECEIPT',deliveries:'DELIVERY',transfers:'TRANSFER'}; const wrap=(res,data)=>res.json({success:true,data});
function num(type){return type==='RECEIPT'?'WH/IN':type==='DELIVERY'?'WH/OUT':'WH/INT'}
for(const [path,type] of Object.entries(types)){
 router.get(`/${path}`,async(req,res,next)=>{try{const filter=req.query.status?` AND d.status=$2`:'';const rows=await query(`SELECT d.*,sw.name "sourceWarehouse",dw.name "destinationWarehouse",COUNT(dl.id)::int "totalItems" FROM documents d LEFT JOIN warehouses sw ON sw.id=d.source_warehouse_id LEFT JOIN warehouses dw ON dw.id=d.destination_warehouse_id LEFT JOIN document_lines dl ON dl.document_id=d.id WHERE d.document_type=$1${filter} GROUP BY d.id,sw.name,dw.name ORDER BY d.created_at DESC`,req.query.status?[type,req.query.status]:[type]);wrap(res,rows.rows)}catch(e){next(e)}});
 router.post(`/${path}`,authorize('ADMIN','INVENTORY_MANAGER','WAREHOUSE_STAFF'),validate(documentSchema),async(req,res,next)=>{const client=await pool.connect();try{await client.query('BEGIN');const b=req.body;const count=await client.query('SELECT COUNT(*)+1 n FROM documents WHERE document_type=$1',[type]);const d=await client.query(`INSERT INTO documents(document_type,document_number,partner_name,source_warehouse_id,source_location_id,destination_warehouse_id,destination_location_id,scheduled_date,status,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[type,`${num(type)}/${String(count.rows[0].n).padStart(5,'0')}`,b.partnerName,b.sourceWarehouseId||null,b.sourceLocationId||null,b.destinationWarehouseId||null,b.destinationLocationId||null,b.scheduledDate||null,b.status,b.notes||null,req.user.id]);for(const l of b.lines)await client.query('INSERT INTO document_lines(document_id,product_id,expected_quantity,processed_quantity,uom) VALUES($1,$2,$3,$4,$5)',[d.rows[0].id,l.productId,l.expectedQuantity,l.processedQuantity||l.expectedQuantity,l.uom]);await client.query('COMMIT');res.status(201);wrap(res,d.rows[0]);}catch(e){await client.query('ROLLBACK');next(e)}finally{client.release()}});
 router.get(`/${path}/:id`,async(req,res,next)=>{try{const d=await query('SELECT * FROM documents WHERE id=$1 AND document_type=$2',[req.params.id,type]);if(!d.rowCount)throw new ApiError(404,'Document not found','NOT_FOUND');const lines=await query(`SELECT dl.*,p.name product,p.sku FROM document_lines dl JOIN products p ON p.id=dl.product_id WHERE dl.document_id=$1`,[d.rows[0].id]);wrap(res,{...d.rows[0],lines:lines.rows})}catch(e){next(e)}});
 router.post(`/${path}/:id/validate`,authorize('ADMIN','INVENTORY_MANAGER','WAREHOUSE_STAFF'),async(req,res,next)=>{const client=await pool.connect();try{await client.query('BEGIN');const d=await client.query('SELECT * FROM documents WHERE id=$1 AND document_type=$2 FOR UPDATE',[req.params.id,type]);if(!d.rowCount)throw new ApiError(404,'Document not found','NOT_FOUND');if(d.rows[0].status==='DONE')throw new ApiError(409,'This document has already been validated','ALREADY_DONE');if(d.rows[0].status==='CANCELED')throw new ApiError(409,'Canceled documents cannot be validated','CANCELED_DOCUMENT');await validateDocument(client,d.rows[0],req.user.id);await client.query('COMMIT');wrap(res,{message:`${d.rows[0].document_number} validated successfully`});}catch(e){await client.query('ROLLBACK');next(e)}finally{client.release()}});
}
router.get('/adjustments',async(_q,res,next)=>{try{wrap(res,(await query(`SELECT a.*,p.name product,w.name warehouse,l.name location FROM inventory_adjustments a JOIN products p ON p.id=a.product_id JOIN warehouses w ON w.id=a.warehouse_id JOIN locations l ON l.id=a.location_id ORDER BY a.created_at DESC`)).rows)}catch(e){next(e)}});
router.post('/adjustments',authorize('ADMIN','INVENTORY_MANAGER','WAREHOUSE_STAFF'),validate(adjustmentSchema),async(req,res,next)=>{const client=await pool.connect();try{await client.query('BEGIN');const b=req.body;const balance=await client.query('SELECT on_hand FROM stock_balances WHERE product_id=$1 AND location_id=$2 FOR UPDATE',[b.productId,b.locationId]);const system=Number(balance.rows[0]?.on_hand||0);const a=await client.query('INSERT INTO inventory_adjustments(product_id,warehouse_id,location_id,system_quantity,counted_quantity,reason,created_by,status) VALUES($1,$2,$3,$4,$5,$6,$7,\'DONE\') RETURNING *',[b.productId,b.warehouseId,b.locationId,system,b.countedQuantity,b.reason,req.user.id]);const delta=b.countedQuantity-system;if(delta)await changeStock(client,{productId:b.productId,warehouseId:b.warehouseId,locationId:b.locationId,delta,movementType:delta>0?'ADJUSTMENT_IN':'ADJUSTMENT_OUT',referenceType:'ADJUSTMENT',referenceId:a.rows[0].id,userId:req.user.id,notes:b.reason});await client.query('COMMIT');res.status(201);wrap(res,a.rows[0]);}catch(e){await client.query('ROLLBACK');next(e)}finally{client.release()}});
router.get('/stock-ledger',async(req,res,next)=>{try{const term=`%${req.query.search||''}%`;wrap(res,(await query(`SELECT sl.*,p.name product,p.sku,w.name warehouse,l.name location FROM stock_ledger sl JOIN products p ON p.id=sl.product_id JOIN warehouses w ON w.id=sl.warehouse_id JOIN locations l ON l.id=sl.location_id WHERE p.name ILIKE $1 OR p.sku ILIKE $1 ORDER BY sl.created_at DESC LIMIT 100`,[term])).rows)}catch(e){next(e)}});
export default router;
